### ISSUE TITLE
Branch unzip-port Ready for Testing

### ISSUE THREAD

**Issue by pikpik** [pikpik/minix-pkgsrc#4]
Hi,

I made a new branch called "unzip-port." It has my changes for archivers/unzip.

This is for the effort of converting packages from using MINIX's C library to using the new NetBSD C library.

I'm unsure of some of the changes, because some involved rewriting legacy "MINIX" flags to be "__minix," which is the current flag used to indicate that the platform being compiled on is MINIX. Would this cause problems on legacy systems? Is that fine, as they shouldn't use these changes anyway? For the current source of MINIX, this change appears to have no negative effects.

Another change of relative uncertainty is the avoidance of sections of code flagged by either "BSD" or "BSD4_4." The reason for this change is that MINIX's new NetBSD C library specifically avoids using the "BSD4_4" flag, but with no indication of why [1]. Although I'm confused about avoiding "BSD4_4" code, as I had assumed enabling such code was part of the purpose of the NetBSD C library on MINIX, this change appears to have no negative effects.

Thanks!
pikpik
1. You can see the avoidance of the "BSD4_4" flag here on lines 9 through 11: http://git.minix3.org/?p=minix.git;a=blob;f=nbsd_include/sys/param.h;h=b750a3ecf215ba5502c3ca3aea51896762e4b654;hb=c63a0cfddcd42e04be6ef8833b3975fbbbbfe802

**Comment by tcort** [comment]
>  rewriting legacy "MINIX" flags to be "__minix,"
> Would this cause problems on legacy systems?

At the moment, Minix's pkgsrc repository is targeted at the current Minix master (i.e. pkgsrc.git/minix-master expects to compile packages with the Minix port of NetBSD libc), so legacy systems won't be using the latest pkgsrc changes. So it isn't a problem.

The patches look good. I'll do some testing and commit them to the Minix pkgsrc repository. Thanks for your help!

**Comment by pikpik** [comment]
Ok, sounds good.

You're very welcome!

Thank you!
pikpik
